# docs
# https://github.com/Huachao/vscode-restclient

@hostname = http://localhost:3333

###
# /auth endpoint
# used for registration and login
POST {{hostname}}/auth/login

###
POST {{hostname}}/auth/signup
content-type: application/json

{
    "email": "jean-luc-picard-3@officers.fleet",
    "password": "HeardThroughTheGrapevine"
}

###
# endpoint throws error
GET {{hostname}}/auth/get-error

###
# /user/everyone gets a list of all registered users
GET {{hostname}}/user/everyone