# docs
# https://github.com/Huachao/vscode-restclient

@hostname = http://localhost:3333

###
POST {{hostname}}/auth/login

###
POST {{hostname}}/auth/signup
content-type: application/json

{
    "email": "jean-luc-picard-3@officers.fleet",
    "password": "HeardThroughTheGrapevine"
}

###
GET {{hostname}}/auth/get-error