version: '3.8'
services:
  starship-db:
    image: postgres:13
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: starship-computer
    networks:
      - starship
networks:
  starship:
